### ISSUE TITLE
Deprecated deps

### ISSUE THREAD

**Issue by xinyuluo** [aluuu/osm_xml#1]
Hi, 

I am working with OSM data recently and find your package to be useful for importing OSM file in OCaml. Yet some dependencies seem old (it requires core < 0.11), which is a struggle for me to use the lib with my project. I tried to submit a PR for upgrading dependencies but got:
```
remote: Permission to aluuu/osm_xml.git denied to xinyuluo.
```
Would you like to make this project open for external contributors? Thank you.

**Comment by aluuu** [comment]
Hello Xinyu, 

Thanks for reaching out.

I think what you are trying to do is to push your changes directly to my repository, for which you don't have permissions. It would be easier for you'd fork my repository to you account (there's a "Fork" button in the top right corner, next to "Star" and "Watch" buttons), push the changes in your own forked repository and then you'd be able to submit a pull request with your changes via GitHub's interface. 

Here's a help article that describes the process a bit - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by xinyuluo** [comment]
Thanks for quick reply @aluuu ! Oki I will try to submit a pull request that way
